name: grow_personal_dev
description: Personal development app (Habits, Journal, Todos, Finance, Timetable, Offline Chatbot)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_sign_in: ^6.3.0
  sqflite: ^2.3.3+2
  path: ^1.9.0
  uuid: ^4.5.2
  connectivity_plus: ^7.0.0
  flutter_local_notifications: ^17.2.4
  intl: ^0.20.2
  image_picker: ^1.2.1
  timezone: ^0.9.4
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.5
  table_calendar: ^3.1.3
  permission_handler: ^11.4.0
  flutter_ringtone_player: ^4.0.0+4
  firebase_ai: ^3.15.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


