// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcMZAE8cSzdIQ3JfOujintV5QgcG20h5A',
    appId: '1:110348386710:web:73131890f4878e7e4a9db7',
    messagingSenderId: '110348386710',
    projectId: 'personal-development-app-60f48',
    authDomain: 'personal-development-app-60f48.firebaseapp.com',
    storageBucket: 'personal-development-app-60f48.firebasestorage.app',
    measurementId: 'G-NCMQXB9QQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKR8kcYunp1bIeUFVi8D0yEcDvNdXgzRE',
    appId: '1:110348386710:android:336827f8b5e81dc44a9db7',
    messagingSenderId: '110348386710',
    projectId: 'personal-development-app-60f48',
    storageBucket: 'personal-development-app-60f48.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj-HdM_Ettl00Irn_E2nMtmdLCUcQNS3g',
    appId: '1:110348386710:ios:e8af09b8e0d9c0524a9db7',
    messagingSenderId: '110348386710',
    projectId: 'personal-development-app-60f48',
    storageBucket: 'personal-development-app-60f48.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
